site_name: ECE196 IOT Documentation
repo_url: https://github.com/curtisrlee/ece196-fall2020-iot
repo_name: ece196-fall2020-iot
edit_uri: ""
nav:
    - Home: index.md
    - Raspberry Pi: rpi.md
    - Firebase: firebase.md
    - VueJS: web.md
    - Bootstrap: bootstrap.md
    - Security: secure.md
    - Graphs: graphs.md
theme:
    name: material
    icon:
      repo: fontawesome/brands/github
markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://www.github.com/curtisrlee
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/curtisrlee
        - icon: fontawesome/brands/facebook
          link: https://www.facebook.com/curtisrlee98